import "../styles/globals.css";
import { useEffect } from "react";
import { store } from "../store/app";
import { Provider } from "react-redux";
import Head from "next/head";
import { appWithTranslation } from "next-i18next";
import { useRouter } from "next/router";
import Loading from "../components/Loading";
import localfont from "next/font/local";
import dynamic from "next/dynamic";
const battambang = localfont({
  src: "../public/fonts/Battambang-Regular.ttf",
});
const roboto = localfont({
  src: "../public/fonts/Roboto-Regular.ttf",
});
const DynamicLayout = dynamic(() => import("../layouts/default"), {
  ssr: false,
});
function App({ Component, pageProps }) {
  const router = useRouter();
  useEffect(() => {
    let timeout;
    if (typeof window !== "undefined") {
      const loader = document.getElementById("globalLoader");
      if (loader) {
        timeout = setTimeout(() => {
          loader.remove();
        }, 3000);
      }
    }
    return () => clearTimeout(timeout);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <Loading />
        <main
          className={
            router.locale === "kh" ? battambang.className : roboto.className
          }
        >
          <DynamicLayout
            font={
              router.locale === "kh" ? battambang.className : roboto.className
            }
          >
            <Component {...pageProps} />
          </DynamicLayout>
        </main>
      </Provider>
    </>
  );
}

export default appWithTranslation(App);
